### ISSUE TITLE
The references behind calculate the angle between the key points

### ISSUE THREAD

**Issue by malareeqi** [yuyoujiang/exercise-counting-with-YOLOv8#2]
Please can you tell me the logic or the math  behind calculating the angle between the keypoints?

**Comment by yuyoujiang** [comment]
Hi malareeqi,
Please focus on `demo.py` line 40-56.
1、`line1` and `line2` are expected to be coordinates representing two lines. Each line is represented by four elements, corresponding to the x and y coordinates of the endpoints of the line (for example, `line1[0]` and `line1[1]` are the x and y coordinates of one endpoint of the first line, `line1[2]` and `line1[3]` are the coordinates of the other endpoint).
2、calculate the slopes of the two lines.
3、convert the calculated radian values to degrees.
4、calculate the difference in angle between the two lines, using absolute value to ensure a positive number.
5、ensure that the calculated angle difference does not exceed 180 degrees.
I hope this can help you
